"""Fixed commodity/FX universe shared by the API and its seed watcher."""

COMMODITY_SYMBOLS = [
    ("vix", "VIX", "^VIX"),
    ("gold", "GOLD", "GC=F"),
    ("silver", "SILVER", "SI=F"),
    ("copper", "COPPER", "HG=F"),
    ("platinum", "PLATINUM", "PL=F"),
    ("palladium", "PALLADIUM", "PA=F"),
    ("aluminum", "ALUMINUM", "ALI=F"),
    ("oil", "OIL", "CL=F"),
    ("brent", "BRENT", "BZ=F"),
    ("natgas", "NATGAS", "NG=F"),
    ("ttf", "TTF GAS", "TTF=F"),
    ("gasoline", "GASOLINE", "RB=F"),
    ("heating-oil", "HEATING OIL", "HO=F"),
    ("uranium", "URANIUM", "URA"),
    ("lithium", "LITHIUM", "LIT"),
    ("coal", "COAL ETF", "COAL"),
    ("wheat", "WHEAT", "ZW=F"),
    ("corn", "CORN", "ZC=F"),
    ("soybeans", "SOYBEANS", "ZS=F"),
    ("rice", "RICE", "ZR=F"),
    ("coffee", "COFFEE", "KC=F"),
    ("sugar", "SUGAR", "SB=F"),
    ("cocoa", "COCOA", "CC=F"),
    ("cotton", "COTTON", "CT=F"),
    ("eurusd", "EUR/USD", "EURUSD=X"),
    ("gbpusd", "GBP/USD", "GBPUSD=X"),
    ("usdjpy", "USD/JPY", "USDJPY=X"),
    ("usdcny", "USD/CNY", "USDCNY=X"),
    ("usdinr", "USD/INR", "USDINR=X"),
    ("audusd", "AUD/USD", "AUDUSD=X"),
    ("usdchf", "USD/CHF", "USDCHF=X"),
    ("usdcad", "USD/CAD", "USDCAD=X"),
    ("usdtry", "USD/TRY", "USDTRY=X"),
]
