from __future__ import annotations

from typing import Any, Dict, Iterable, List


TRUSTED_HLS_SOURCES: tuple[Dict[str, Any], ...] = (
    {
        "id": "trusted-hls-bloomberg",
        "displayName": "Bloomberg TV HLS",
        "category": "macro",
        "region": "global",
        "country": "US",
        "language": "en",
        "hlsUrl": "https://bloomberg.com/media-manifest/streams/us.m3u8",
        "externalUrl": "https://www.bloomberg.com/live",
        "marketTags": ["macro", "fed", "rates", "stocks", "fx", "commodities"],
        "marketUseCase": "Trusted HLS fallback for macro, central bank, equities, FX, and commodities markets.",
    },
    {
        "id": "trusted-hls-cnbc",
        "displayName": "CNBC Live HLS",
        "category": "macro",
        "region": "americas",
        "country": "US",
        "language": "en",
        "hlsUrl": "https://cdn-ca2-na.lncnetworks.host/hls/cnbc_live/index.m3u8",
        "externalUrl": "https://www.cnbc.com/live-tv/",
        "marketTags": ["stocks", "fed", "rates", "macro", "earnings", "oil"],
        "marketUseCase": "Proxied trusted HLS path for US market-moving business news.",
        "hlsProxyRequired": True,
        "hlsProxyReferer": "https://livenewschat.eu/",
    },
    {
        "id": "trusted-hls-sky-news",
        "displayName": "Sky News HLS",
        "category": "breaking",
        "region": "europe",
        "country": "GB",
        "language": "en",
        "hlsUrl": "https://linear901-oo-hls0-prd-gtm.delivery.skycdp.com/17501/sde-fast-skynews/master.m3u8",
        "externalUrl": "https://news.sky.com/watch-live",
        "fallbackVideoId": "uvviIF4725I",
        "marketTags": ["breaking", "uk", "europe", "politics", "geopolitics"],
        "marketUseCase": "High-confidence HLS path for breaking UK and Europe news markets.",
    },
    {
        "id": "trusted-hls-euronews",
        "displayName": "Euronews HLS",
        "category": "news",
        "region": "europe",
        "country": "EU",
        "language": "en",
        "hlsUrl": "https://dash4.antik.sk/live/test_euronews/playlist.m3u8",
        "externalUrl": "https://www.euronews.com/live",
        "fallbackVideoId": "pykpO5kQJ98",
        "marketTags": ["europe", "eu", "politics", "breaking", "macro"],
        "marketUseCase": "Trusted Europe-first live stream for EU policy, elections, and regional event markets.",
    },
    {
        "id": "trusted-hls-dw",
        "displayName": "DW News HLS",
        "category": "geopolitics",
        "region": "europe",
        "country": "DE",
        "language": "en",
        "hlsUrl": "https://dwamdstream103.akamaized.net/hls/live/2015526/dwstream103/master.m3u8",
        "externalUrl": "https://www.dw.com/en/media-center/live-tv/s-100825",
        "fallbackVideoId": "LuKwFajn37U",
        "marketTags": ["germany", "europe", "geopolitics", "war", "policy"],
        "marketUseCase": "Trusted European geopolitical stream with YouTube fallback.",
    },
    {
        "id": "trusted-hls-france24",
        "displayName": "France 24 English HLS",
        "category": "geopolitics",
        "region": "europe",
        "country": "FR",
        "language": "en",
        "hlsUrl": "https://amg00106-france24-france24-samsunguk-qvpp8.amagi.tv/playlist/amg00106-france24-france24-samsunguk/playlist.m3u8",
        "externalUrl": "https://www.france24.com/en/live",
        "fallbackVideoId": "Ap-UM1O9RBU",
        "marketTags": ["france", "europe", "geopolitics", "africa", "diplomacy"],
        "marketUseCase": "Trusted international news stream for Europe, Africa, and diplomatic markets.",
    },
    {
        "id": "trusted-hls-aljazeera",
        "displayName": "Al Jazeera English HLS",
        "category": "geopolitics",
        "region": "middle-east",
        "country": "QA",
        "language": "en",
        "hlsUrl": "https://live-hls-apps-aje-fa.getaj.net/AJE/index.m3u8",
        "externalUrl": "https://www.aljazeera.com/live",
        "fallbackVideoId": "gCNeDWCI0vo",
        "marketTags": ["middle-east", "conflict", "geopolitics", "war", "diplomacy"],
        "marketUseCase": "Trusted Middle East and conflict-heavy live news stream.",
    },
    {
        "id": "trusted-hls-alarabiya",
        "displayName": "Al Arabiya HLS",
        "category": "geopolitics",
        "region": "middle-east",
        "country": "SA",
        "language": "ar",
        "hlsUrl": "https://live.alarabiya.net/alarabiapublish/alarabiya.smil/playlist.m3u8",
        "externalUrl": "https://www.alarabiya.net/live-stream",
        "fallbackVideoId": "n7eQejkXbnM",
        "marketTags": ["middle-east", "gulf", "oil", "conflict", "diplomacy"],
        "marketUseCase": "Trusted Gulf and Middle East live stream for conflict, oil, and diplomacy markets.",
    },
    {
        "id": "trusted-hls-abc-news",
        "displayName": "ABC News Live HLS",
        "category": "news",
        "region": "americas",
        "country": "US",
        "language": "en",
        "hlsUrl": "https://lnc-abc-news.tubi.video/index.m3u8",
        "externalUrl": "https://abcnews.go.com/Live",
        "marketTags": ["us", "breaking", "politics", "elections", "weather"],
        "marketUseCase": "Trusted US live news stream for politics, elections, and breaking event markets.",
    },
    {
        "id": "trusted-hls-cbs-news",
        "displayName": "CBS News HLS",
        "category": "news",
        "region": "americas",
        "country": "US",
        "language": "en",
        "hlsUrl": "https://cbsn-us.cbsnstream.cbsnews.com/out/v1/55a8648e8f134e82a470f83d562deeca/master.m3u8",
        "externalUrl": "https://www.cbsnews.com/live/",
        "fallbackVideoId": "R9L8sDK8iEc",
        "marketTags": ["us", "breaking", "politics", "elections", "economy"],
        "marketUseCase": "Trusted US live news stream for politics and election markets.",
    },
    {
        "id": "trusted-hls-nbc-news",
        "displayName": "NBC News Now HLS",
        "category": "news",
        "region": "americas",
        "country": "US",
        "language": "en",
        "hlsUrl": "https://dai2.xumo.com/amagi_hls_data_xumo1212A-xumo-nbcnewsnow/CDN/master.m3u8",
        "externalUrl": "https://www.nbcnews.com/now",
        "fallbackVideoId": "yMr0neQhu6c",
        "marketTags": ["us", "breaking", "politics", "elections", "weather"],
        "marketUseCase": "Trusted US rolling news stream for event and policy markets.",
    },
    {
        "id": "trusted-hls-cgtn",
        "displayName": "CGTN English HLS",
        "category": "geopolitics",
        "region": "asia",
        "country": "CN",
        "language": "en",
        "hlsUrl": "https://news.cgtn.com/resource/live/english/cgtn-news.m3u8",
        "externalUrl": "https://www.cgtn.com/tv",
        "marketTags": ["china", "asia", "geopolitics", "trade", "policy"],
        "marketUseCase": "Trusted China and Asia live stream for geopolitics and macro policy markets.",
    },
    {
        "id": "trusted-hls-nhk-world",
        "displayName": "NHK World HLS",
        "category": "geopolitics",
        "region": "asia",
        "country": "JP",
        "language": "en",
        "hlsUrl": "https://nhkwlive-ojp.akamaized.net/hls/live/2003459/nhkwlive-ojp-en/index_4M.m3u8",
        "externalUrl": "https://www3.nhk.or.jp/nhkworld/en/live/",
        "fallbackVideoId": "f0lYfG_vY_U",
        "marketTags": ["japan", "asia", "geopolitics", "earthquake", "policy"],
        "marketUseCase": "Trusted Japan and Asia stream for regional policy and disaster markets.",
    },
    {
        "id": "trusted-hls-trt-world",
        "displayName": "TRT World HLS",
        "category": "geopolitics",
        "region": "middle-east",
        "country": "TR",
        "language": "en",
        "hlsUrl": "https://tv-trtworld.medya.trt.com.tr/master.m3u8",
        "externalUrl": "https://www.trtworld.com/live",
        "fallbackVideoId": "ABfFhWzWs0s",
        "marketTags": ["turkey", "middle-east", "geopolitics", "war", "diplomacy"],
        "marketUseCase": "Trusted Turkey and Middle East stream for conflict and diplomacy markets.",
    },
    {
        "id": "trusted-hls-sky-news-arabia",
        "displayName": "Sky News Arabia HLS",
        "category": "geopolitics",
        "region": "middle-east",
        "country": "AE",
        "language": "ar",
        "hlsUrl": "https://live-stream.skynewsarabia.com/c-horizontal-channel/horizontal-stream/index.m3u8",
        "externalUrl": "https://www.skynewsarabia.com/live",
        "fallbackVideoId": "U--OjmpjF5o",
        "marketTags": ["middle-east", "gulf", "conflict", "oil", "diplomacy"],
        "marketUseCase": "Trusted Arabic live stream for Gulf and Middle East markets.",
    },
    {
        "id": "trusted-hls-al-hadath",
        "displayName": "Al Hadath HLS",
        "category": "geopolitics",
        "region": "middle-east",
        "country": "SA",
        "language": "ar",
        "hlsUrl": "https://av.alarabiya.net/alarabiapublish/alhadath.smil/playlist.m3u8",
        "externalUrl": "https://www.alhadath.net/live-stream",
        "fallbackVideoId": "xWXpl7azI8k",
        "marketTags": ["middle-east", "conflict", "war", "gulf", "diplomacy"],
        "marketUseCase": "Trusted Arabic breaking news stream for conflict and diplomacy markets.",
    },
    {
        "id": "trusted-hls-reuters-tv",
        "displayName": "Reuters TV HLS",
        "category": "news",
        "region": "global",
        "country": "GB",
        "language": "en",
        "hlsUrl": "https://reuters-reutersnow-1-eu.rakuten.wurl.tv/playlist.m3u8",
        "externalUrl": "https://www.reuters.com/video/",
        "marketTags": ["breaking", "world", "macro", "policy", "markets"],
        "marketUseCase": "Trusted wire-style video stream for major global news and market-moving events.",
    },
    {
        "id": "trusted-hls-the-guardian",
        "displayName": "The Guardian HLS",
        "category": "news",
        "region": "europe",
        "country": "GB",
        "language": "en",
        "hlsUrl": "https://rakuten-guardian-1-ie.samsung.wurl.tv/playlist.m3u8",
        "externalUrl": "https://www.theguardian.com/video",
        "marketTags": ["uk", "europe", "politics", "climate", "world"],
        "marketUseCase": "Trusted video stream for UK, Europe, climate, and global politics markets.",
    },
    {
        "id": "trusted-hls-arirang-news",
        "displayName": "Arirang News HLS",
        "category": "geopolitics",
        "region": "asia",
        "country": "KR",
        "language": "en",
        "hlsUrl": "https://amdlive-ch01-ctnd-com.akamaized.net/arirang_1ch/smil:arirang_1ch.smil/playlist.m3u8",
        "externalUrl": "https://www.arirang.com/live",
        "marketTags": ["korea", "asia", "geopolitics", "trade", "policy"],
        "marketUseCase": "Trusted Korea and Asia stream for regional geopolitics and trade markets.",
    },
    {
        "id": "trusted-hls-fox-weather",
        "displayName": "FOX Weather YouTube Fallback",
        "category": "weather",
        "region": "americas",
        "country": "US",
        "language": "en",
        "hlsUrl": "https://fox-foxweathernow-samsungus.amagi.tv/playlist.m3u8",
        "externalUrl": "https://www.foxweather.com/live",
        "fallbackVideoId": "qCJeN57DKls",
        "marketTags": ["weather", "hurricane", "storm", "flood", "temperature"],
        "marketUseCase": "Trusted weather stream candidate for severe weather markets with YouTube fallback.",
    },
)


def trusted_hls_items(*, generated_at: str) -> List[Dict[str, Any]]:
    output: List[Dict[str, Any]] = []
    for source in TRUSTED_HLS_SOURCES:
        item = dict(source)
        item.update(
            {
                "sourceRole": item.get("sourceRole") or "channel",
                "sourceType": "hls",
                "sourceName": item.get("sourceName") or "worldmonitor-trusted-hls",
                "sourceUrl": item.get("sourceUrl") or item.get("hlsUrl"),
                "quality": item.get("quality") or "trusted",
                "status": item.get("status") or "ready",
                "availability": item.get("availability") or "public",
                "matchedTerms": item.get("matchedTerms") or list(item.get("marketTags") or [])[:4],
                "lastCheckedAt": generated_at,
                "playbackTier": "trusted-hls",
                "playbackStrategy": "proxied-hls" if item.get("hlsProxyRequired") else "direct-hls",
            }
        )
        output.append(item)
    return output


def trusted_hls_urls() -> Iterable[str]:
    for source in TRUSTED_HLS_SOURCES:
        url = str(source.get("hlsUrl") or "").strip()
        if url:
            yield url
